fix(build): bring back the `.m2-ro` idea
syndesisio/syndesis-pipeline-library pull request #21
Opened 2017-08-24 10:55 UTC by zregvart

We need to mount the `m2-settings` kubernetes secret, if we mount it to
`.../.m2` then other files cannot be reliably written there. As a
workaround let's mount it to `.../.m2-ro` and copy the content over to
`.../.m2`.

2017-08-24 22:11 UTC, zregvart commented
@iocanel could you have a look the repository permissions don't allow me to assign you as a reviewer, thanks 👍

2017-08-25 08:39 UTC, iocanel requested changes
The problem we are trying to solve is that we have limitations (space and/or permission) writing under `.m2` because we are mounting a secret under .m2 and secrets have a limited capacity (so we can't just download the internet there).

The actual solution to the problem is to have kubenretes-plugin support secret subpaths, so that we can just mount `.m2/settings.xml`. This should be trivial given that we maintain our own fork of the plugin.

The current workaround we use for the maven local repo is to use `inception style` volume mounts (a volume mount within a volume mount). I think that we could possibly do the same for the mvnw issues we have too (i.e. mount an empty dir under `.m2/wrapper` or whatever is the path we want to use).

2017-08-25 08:39 UTC, iocanel commented on vars/inside.groovy
> +            sh '''
I don't like the fact that handling of maven repositories / settings is leaking to non-maven related functions like this.

2017-08-25 08:47 UTC, rawlingsj commented
FWIW we mount the maven settings and .m2 folders in a different locations, then in the settings.xml change the location with this..
```
<settings>
  <!-- sets the local maven repository outside of the ~/.m2 folder for easier mounting of secrets and repo -->
  <localRepository>${user.home}/.mvnrepository</localRepository>

```

This is the shared pipeline library
https://github.com/fabric8io/fabric8-pipeline-library/blob/master/vars/mavenTemplate.groovy#L45-L46

2017-08-25 09:26 UTC, zregvart commented
let's close this and rollback for now and come back when we can do subpaths

2017-08-25 09:26 UTC, closed without merging